---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: urpmi
no_index:
  directory:
    - t
    - inc
requires:
  Locale::gettext: 1.01
  MDV::Packdrakeng: 1.01
  URPM: 4.15
version: v7.27.4
